### ISSUE TITLE
Git tag for 1.3.1 (and following releases)

### ISSUE THREAD

**Issue by SpotlightKid** [oxesoft/oxefmsynth#1]
Could you tag each new release in Git?

This would make it easier to package oxefmsynth for Linux distribution packages built from source for a specific release.

**Comment by oxesoft** [comment]
Thank you! I forgot to make it, but I'll do it now. :-)


Daniel Moura
@danielgvmoura <http://twitter.com/danielgvmoura>
oxesoft@gmail.com
http://www.oxesoft.com

2015-09-26 14:55 GMT-03:00 Christopher Arndt <notifications@github.com>:
