### ISSUE TITLE
Black window instead of gui

### ISSUE THREAD

**Issue by bunyi** [oxesoft/oxefmsynth#12]
It is not possible to use gui as I can only see a black window.
plugin built from sources ([AUR](https://aur.archlinux.org/packages/oxefmsynth))
Arch Linux x86_64, kernel 4.4.5-1-ARCH, gcc 5.3.0, mesa 11.1.2-1, nvidia 361.28-4
Tested hosts: Bitwig Studio, Renoise, Ardour

Binary version does not load at all with message (undefined symbol: glDrawArrays)

**Comment by oxesoft** [comment]
It was fixed in Dec 23, 2015 by [https://github.com/oxesoft/oxefmsynth/commit/e56552cd59c67b6543523455cbe001a1b1b7e583](this) commit. I didn't create a tag after this because I thought it was not enough.

**Comment by oxesoft** [comment]
I could create a new tag you could remove the mesa dependecy from arch linux package. First, I want you test the HEAD revision and confirm it is OK.

**Comment by bunyi** [comment]
I was able to compile oxefmsynth manually and this build works perfectly.

**Comment by oxesoft** [comment]
tag created
