### ISSUE TITLE
osx

### ISSUE THREAD

**Issue by simonfan** [oxesoft/oxefmsynth#3]
@oxesoft me dá uma ideia de como rodar num osx? só com VM mesmo? preciso de uma luz, hahaha, C definitivamente não é a minha praia... até tentei fazer o build dentro de um docker, mas por motivos óbvios que pensei agora isso não faz sentido nenhum hahaha.

**Comment by oxesoft** [comment]
Para rodar num OSX é necessário fazer o porting para que ele rode como um
plugin VST nativo para Mac. Isso está nos meus planos assim que conseguir
um Mac por uns dias.
----------
To run on OSX is necessary to make the porting to a native VST for Mac. It
is on my plans as soon as I borrow a Mac for some days.


Daniel Moura
@danielgvmoura <http://twitter.com/danielgvmoura>
oxesoft@gmail.com
http://www.oxesoft.com

Em 5 de outubro de 2015 23:05, Simon Fan <notifications@github.com>
escreveu:
