### ISSUE TITLE
Can't set up Mingw for OxeFMSynth + scaling issues?

### ISSUE THREAD

**Issue by ghost** [oxesoft/oxefmsynth#31]
**SOLVED:** [Oxe Synth is really small, and is hard to use, especially for a beginner. I wish, if there were a drop-down option, or maybe for now, a bigger GUI. Is it possible to do that?]

And would there be a guide on how to build for Windows? I think that I have mingw - which comes preinstalled with Git Bash, or Railsinstaller. What next? Because maybe, I could figure it for myself?

**Comment by mkruselj** [comment]
No definitely install mingw separately, then try.

Also, check out https://github.com/oxesoft/oxefmsynth/pull/28

**Comment by ghost** [comment]
@mkruselj thanks for highlighting the issue. I've tried Mingw from Win-build, as well as Cygwin, but it wasn't working. Finally, tried the Mingw-w64, and the environment seems to be working well, except for the build error.

```
PS C:\Users\ashvi\Documents\GitHub\oxefmsynth> mingw32-make.exe
process_begin: CreateProcess(NULL, uname -s, ...) failed.
mingw32-make: Makefile:17: pipe: No error
"Building converter"
"Building demo"
"Building standalone"
process_begin: CreateProcess(NULL, uname -s, ...) failed.
mingw32-make[1]: Makefile.standalone:45: pipe: No error
In file included from src/standalone/main.cpp:22:
C:/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/i686-w64-mingw32/include/stdio.h:735:23: error: conflicting declaration of 'int _snprintf(char*, size_t, const char*, ...)' with 'C' linkage      
   _CRTIMP int __cdecl _snprintf(char * __restrict__ _Dest,size_t _Count,const char * __restrict__ _Format,...) __MINGW_ATTRIB_DEPRECATED_SEC_WARN;
                       ^~~~~~~~~
In file included from src/synth/synthesizer.h:19,
                 from src/gui/editor.h:19,
                 from src/standalone/main.cpp:19:
src/synth/constants.h:163:22: note: previous declaration with 'C++' linkage
     #define snprintf _snprintf
                      ^~~~~~~~~
src/toolkits/windowstoolkit.cpp:156:35: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
     StringCchCatA(path, MAX_PATH, "\\"BMP_PATH);
                                   ^
mingw32-make[1]: *** [Makefile.standalone:103: all] Error 1
mingw32-make: *** [Makefile:25: all] Error 2 
```

Just realized that this works without any popups in Git Bash, so probably, this is the Makefile not configured properly for Windows.
uname -s is a UNIX command, I guess.
