### ISSUE TITLE
Where can I find vstsdk2.4?

### ISSUE THREAD

**Issue by steevbatt** [oxesoft/oxefmsynth#32]
I'm trying to compile from clone of this repository on Fedora 32. Converter/demo/standalone are working, but VST build gives me this:
_Makefile.vstlinux:18: *** Please set the VSTSDK_PATH environment variable to the vstsdk2.4 path.  Stop.
make: *** [Makefile:27: all] Error 2_

Links to vstsdk2.4 on steinberg site are all broken. Can someone add it to this repo?

**Comment by oxesoft** [comment]
[vst_sdk2_4_rev2.zip](https://drive.google.com/file/d/0B35KOur9xAAYOGRhNjVjMjMtMjY3MC00N2NmLWFjZDktMWZjNWI1N2Y2NGFj/view?usp=sharing)
