### ISSUE TITLE
Makefile.vstlinux is missing -lGL in LIBS

### ISSUE THREAD

**Issue by SpotlightKid** [oxesoft/oxefmsynth#5]
I got "undefined symbol: glDrawArrays" when I tried the new version 1.3.4, which I fixed by adding"-lGL" to `LIBS` on line 57 in `Makefile.vstlinux`.

**Comment by ensonic** [comment]
Has the new version been released. I've got oxevst134.zip from drive (https://oxesoft.wordpress.com/) and it fails with this issue. The latest tag is v1.3.5 which means I would expect an oxevst135.zip.
