### ISSUE TITLE
Black GUI on Linux

### ISSUE THREAD

**Issue by adsn** [oxesoft/oxefmsynth#8]
Hi,

I managed to build the latest version of OXE on Linux and the VST works inside recent Bitwig soundwise.
The GUI though is black inside the host as well as in the standalone version.

Do I put a skin folder next to the vst plugin into my vst path to use the skin inside my host
like I should with the standalone version?

I'm on Linux Xubuntu 15.10 XFCE 4.12.

**Comment by oxesoft** [comment]
Please paste here the output of the standalone. The mine is:
default depth=24
OpenGL mode
visual info values:
    depth       : 24
    red_mask    : 00FF0000
    green_mask  : 0000FF00
    blue_mask   : 000000FF
full blitting time: 0ms

**Comment by adsn** [comment]
Same here:

default depth=24
OpenGL mode
visual info values:
    depth       : 24
    red_mask    : 00FF0000
    green_mask  : 0000FF00
    blue_mask   : 000000FF
full blitting time: 0ms

**Comment by oxesoft** [comment]
Please change the line src/toolkits/xlibtoolkit.cpp:239 by "openGLmode = false;" and let me know the result.

**Comment by jpotier** [comment]
Same here : /
Unfortunately I don't have the standalone installed, only the VST
I'm also on Linux and I'm loading the VST in Renoise3

**Comment by adsn** [comment]
Changing to "openGLmode" = false; works, thanks a lot!

Output is:

default depth=24
blitting mode
visual info values:
    depth       : 24
    red_mask    : 00FF0000
    green_mask  : 0000FF00
    blue_mask   : 000000FF
full blitting time: 0ms

BTW, I made some skins:
https://www.dropbox.com/s/f8r1t7fty5pokfn/skins.zip?dl=0

**Comment by oxesoft** [comment]
fixed in https://github.com/oxesoft/oxefmsynth/commit/e56552cd59c67b6543523455cbe001a1b1b7e583
