### ISSUE TITLE
oxe linux vst crashes Ardour 4.4

### ISSUE THREAD

**Issue by dab3-2014** [oxesoft/oxefmsynth#9]
Hi...The latest version 1.3.4 crashes Ardour 4.4.621+r14315 in Linux Mint 17.3 64bit. I downloaded the plugin tar, then put the so files in ~/.vst. Ardour sees the plugin but inserting it into a track all by itself crashes Ardour. Running Ardour from terminal, here's the error displayed:

`actually writing state to /home/mo/Numero Uno/Numero Uno.tmp
renaming state to /home/mo/Numero Uno/Numero Uno.ardour
/usr/lib/x86_64-linux-gnu/ardour4/ardour-4.4.621+r14315: symbol lookup error: /home/mo/.vst/oxe/oxevst64.so: undefined symbol: glXQueryExtension`

Please let me know if you need any further information to reproduce this issue. Thanks!

**Comment by oxesoft** [comment]
Hi. Could you build the latest repository version? It was already fixed.
